//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSKManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kursanci
    {
        public int Id_Kursanta { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<int> NumerPKK { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string Kod_Pocztowy { get; set; }
        public string Ulica { get; set; }
        public Nullable<int> Id_Pracownika { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
