//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSKManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pojazdy
    {
        public string nr_Rejestracyjny { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> DataZakupu { get; set; }
    }
}
